---
title: "Statistical Epistasis Is a Generic Feature of Gene Regulatory Networks"
date: 2018-01-06T10:23:56-06:00
author: "Yanyu Liang"
tags: ["epistasis in evolution"]
categories: ["biology - research review"]
draft: false
output:
  blogdown::html_page:
    toc: true
    toc_depth: 1
---

# Meta data of reading

* **Journal**: Genetics
* **Year**: 2007
* **DOI**: 10.1534/genetics.106.058859

# Main question

It has been found that even in yeast, the GWAS analysis of statistical epistasis varies a lot between different genetic variation. The question is whether such difference is due to the different functional dependency patterns between genes (regulatory architecture).

# Method and result in brief

This paper takes the approach that focuses on 12 regulatory motifs and simulates data on the basis of these dynamical system. Then, they perform statistical analysis to search for evidence of statistical epistasis. Their finding is that, at significance level 5% two-way and three-way (population size is ~ 1000), there is statistical epistasis signal but the strength is weak (without multiple hypothesis testing correction). Also, three-way gives weaker signal than two-way, which indicates that network complexity may reduce the power. Additionally, this analysis is an oversimplified version of the reality. Even if they argued that the interaction in motif may represent indirect effect, but whether such effect can be simplified is questionable. So, overall, the insight of this paper is that even if there is underlying functional epitasis, to identify statistical epistasis from data is hard.
