---
title: "The background puzzle: how identical mutations in the same gene lead to different disease symptoms"
date: 2018-01-01T10:04:05-06:00
author: "Yanyu Liang"
tags: ["epistasis", 'complex trait']
categories: ["biology - research review"]
draft: false
output:
  blogdown::html_page:
    toc: true
    toc_depth: 1
---

# Meta data of reading

* **Journal**: FEBS
* **Year**: 2017
* **DOI**: 10.1111/febs.14080

# Terminology

This paper discusses the current insights about the phenotypic variation caused by gene interaction, epigenetics and stochasticity in model organism.

## Penetrance and expressivity

Penetrance (according to [wikipedia](https://en.wikipedia.org/wiki/Penetrance)) is the proportion of individuals with the variant (allele) that also express an associated trait (phenotype).

Expressivity (according to [this note](https://www.nature.com/scitable/topicpage/phenotype-variability-penetrance-and-expressivity-573#)) is the degree to which the trait expression differs among individuals. For instance, there is a polydactyly (extra toes) trait in inbreeding cats. Individual carriers may have different number of extra toes. Therefore expressivity is only meaningful when the trait is quantitatively measurable in some sense. An extreme case is that the trait/disease is binary, in which the expressivity for an individual is the trait/disease state. And its population average is penetrance.

## Genetic background effect and examples

It has been found that there are cases where the individual carries the Mendelian disease causing mutation but has no disease symptom. It implies that the incomplete penetrance may depend on the genetic background. The genetic background includes the genes that affect/interact with the disease causing genes.

Also, the same disease with the same mutated genes (involves multiple loci), the expressivity is different among loci, which can also result from the various genetic background.

Cystic fibrosis is monogenic disease. 50% patients carry the same disease causing allele but the disease symptoms are highly variable because of the modifier background genes. There is also case where pedigree-specific phenotype is found. In such case, the same exon deletion causes one syndrome in one pedigree but a more severe one in another.

# Experimental evidence of genetic background effects

## Single gene mutations depend on multiple background loci

The idea is that the expressivity and penetrance of a mutation $M$ is the function of $M$ and the interaction between $M$ and $B$. There are experimental support of $M \times B$ effect in fruit flies and mice.

## Genome-wide and molecular insights into background interactions

Using RNAi researchers have looked for the background interaction in $C. elegans$. The studies indicate that

  1. The effect of background interact is small individually but big together.
  2. The effect may depend on the expression level of the affected gene

## Cryptic genetic variants

Cryptic genetic variants are SNVs that show phenotypic effect under atypical conditions. Such studies imply that gene regulatory network may play a role in genetic background effects. Also, disease-related signaling pathway may be enriched for CGVs.

## The contribution of genetic background is ignored by current genetic research

The effect of genetic background can confound the result so geneticists tend to remove such confounding factor by using organisms with single genetic background. This strategy is to maximize the reproducibility but it miss the genetic background effect which is of great importance in understanding the phenotypic variability of human diseases.

The author points out the general experimental framework to study genetic background effect using model organism. With two populations, $M \times B_1$ and $M \times B_2$ where both of them have disease causing mutation but only one of them has phenotype. By crossing the two populations and performing linkage analysis, the locus associated with the background effect can be identified.

Besides genetic background effects, the phenotypic effects of a mutation can differ in the population with the same genetic background due to environmental effects and stochastic effects.

# Environmental effects

$G \times E$ interactions also contribute to disease risk. It has been found the cholesterol level and cardiovascular disease have different effects across generations. Also the genetic background and environmental factors (diet) act jointly on the outcome.

# Stochastic and epigenetic effects

Chaperon acts as the mutation buffering system which can decrease the penetrance (the function of chaperon can also be affected by environment, i.e. stress). Also, epigenetic effect can lead to different outcomes in individuals with the same genetic background.

# Summary

`r htmltools::HTML("{{< figure src=\"/notebook/images/genetic_background_effect.png\" title=\"Illustration of the genetic background effect\" >}}")`

Genetic background acts through gene-gene interaction, epigenetics adn stochasticity and it is as important as disease-causing mutations. Research also finds that *the mutations in the same gene can increase the severity of many complex psychiatric disorders, which indicates that the effect of genetic background can be pervasive and complex*.
